version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: backend
    container_name: flask-swagger
    volumes:
      - ..:/app
    command: sleep infinity
    environment:
      FLASK_APP: "wsgi:app"
      FLASK_DEBUG: "True"
      DATABASE_URI: "postgresql://postgres:postgres@postgres:5432/postgres"
    networks:
      - dev
    depends_on:
      - postgres

  # PostgreSQL database
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres_data:

networks:
  dev: