name: CI Build
on:
  push:
    branches:
      - master
    paths-ignore:
    - 'README.md'
    - '.vscode/**'

  pull_request:
    branches:
      - master
    paths-ignore:
    - 'README.md'
    - '.vscode/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install -U pip poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Run unit tests with pytest
        run: pytest --pspec --cov=service --cov-fail-under=95 --disable-warnings
        env:
          FLASK_APP: "wsgi:app"
          DATABASE_URI: "postgresql://postgres:postgres@postgres:5432/postgres"

      - name: Upload code coverage
        uses: codecov/codecov-action@v3.1.4

